blog/urls.py
from django.urls import path, include
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', all_blogs, name='all_blogs'),
    path('<int:blog_id>/', detail, name='detail')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
    path('portfolio/', portfolio, name='portfolio'),
    path('contact/', ContactView.as_view(), name='contact')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(
        max_length=255,
        blank=True,
        db_index=True,
        verbose_name='Заголовок'
    )

    description = models.TextField(
        verbose_name='Текст'
    )


    date = models.DateTimeField(
        verbose_name='Дата'
    )



    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):

    title = models.CharField(
        max_length=255,
        db_index=True,
        blank=True,
        verbose_name="Название"
    )

    description = models.CharField(
        max_length=255,
        db_index=True,
        verbose_name="Описание"
    )

    image = models.ImageField(
        upload_to='portfolio/images/',
        verbose_name='Изображение'
    )

    url = models.URLField(
        blank=True
    )

    def __str__(self):
        return self.title


class Skill(models.Model):

    title = models.CharField(
        db_index=True,
        max_length=60,
        blank=True,
        verbose_name='Название'
    )

    score = models.IntegerField(
        db_index=True,
        blank=True,
        default=70
    )

    def __str__(self):
        return self.title


class ContactProfile(models.Model):
    class Meta:
        verbose_name_plural = 'Contact Profiles'
        verbose_name = 'Contact Profile'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(
        auto_now_add=True
    )
    name = models.CharField(
        verbose_name="Name", max_length=100
    )
    email = models.EmailField(
        verbose_name="Email"
    )
    message = models.TextField(
        verbose_name="Message"
    )

    def __str__(self):
        return f'{self.name}'


class Certificate(models.Model):

    title = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Название'
    )

    date = models.DateTimeField(
        blank=True,
        null=True
    )

    name = models.CharField(
        max_length=100,
        blank=True,
        verbose_name="Название курса"
    )

    description = models.TextField(
        verbose_name='Описание'
    )

    def __str__(self):
        return self.title

portfolio/forms.py
from django import forms
from .models import ContactProfile


class ContactForm(forms.ModelForm):

	name = forms.CharField(max_length=100, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Full name..',
			'class': 'form-control'
			}))
	email = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={
			'placeholder': '*Email..',
			'class': 'form-control'
			}))
	message = forms.CharField(max_length=1000, required=True,
		widget=forms.Textarea(attrs={
			'placeholder': '*Message..',
			'class': 'form-control',
			'rows': 6,
			}))


	class Meta:
		model = ContactProfile
		fields = ('name', 'email', 'message',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    context = {
        'blogs':blogs
    }

    return render(request, template_name='blog.html', context=context)

def detail(request, blog_id):

    blog = get_object_or_404(Blog, pk=blog_id)

    context = {'blog':blog}
    return render(request, template_name='blog-detail.html', context=context)

portfolio/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import *
from django.views import generic
from . forms import ContactForm

def home(request):
    skills = Skill.objects.all()
    certificates = Certificate.objects.all()
    context = {
        'skills': skills,
        'certificates': certificates
    }
    return render(request,
                  template_name='index.html', context=context)

def portfolio(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request,
                  template_name='portfolio.html', context=context)


class ContactView(generic.FormView):
    template_name = "contact.html"
    form_class = ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Thank you. We will be in touch soon.')
        return super().form_valid(form)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>kb-bek</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href=""/>
    <link rel="home" href=""/>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'portfolio/images/mainlogo.png' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'portfolio/images/mainlogo.png' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'portfolio/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>

    <!-- ================================
    Start Navigation Bar
    ================================= -->
    <header>
      <div class="headerCol">
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-auto">
              <div class="logoCol"><a href="{% url 'home' %}"><img src="{% static 'portfolio/images/mainlogo.png'%}  " width="85" height="60" alt="..."></a></div>
            </div>
            <div class="col">
              <div class="d-md-none">
                <button class="navToggle">
                  <span class="navToggle__text">Toggle Menu</span>
                </button>
              </div>
              <div class="navCollapseCol">
                <div class="navCol">
                  <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'portfolio' %}">Portfolio</a></li>
                    <li><a href="{% url 'blog:all_blogs' %}">Blog</a></li>
                    <li><a href="https://github.com/kb-bek">GitHub</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- ================================
    End Navigation Bar
    ================================= -->
      {% block content %}
      {% endblock content %}
    <!-- ================================
    Start Content
    ================================= -->

    <footer>
      <div class="footerCol">
        <div class="container">
          <ul class="socialCol">

            <li><a href="https://www.instagram.com/kubageek/"><img src="{% static 'portfolio/images/instagram.png' %}" alt="..."></a></li>
            <li><a href="https://t.me/kbnchbek"><img src="{% static 'portfolio/images/telegram.png' %}" alt="..."></a></li>
            <li><a href="https://www.linkedin.com/in/kubanychbek-talipov-398a60243/"><img src="{% static 'portfolio/images/linkedin.png' %}" alt="..."></a></li>
            <li><a href="https://github.com/kb-bek"><img src="{% static 'portfolio/images/github.png' %}" alt="..."></a></li>
          </ul>
          <div class="copyrightCol">
            <p></p>
          </div>
        </div>
      </div>
    </footer>
    <!-- ================================
    End Footer
    ================================= -->

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'portfolio/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'portfolio/js/script.js' %}"></script>
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

templates/blog-detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h6 class="xlTitle pb-md-3">{{ blog.title }}</h6>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md">
              <h4 class="smTitle pb-3">{{ blog.date|date:'F jS Y' }}</h4>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="sectionSpaceSm">
        <div class="container">
          <p>
            {{ blog.description|safe }}
          </p>
        </div>
      </div>
    </section>


{% endblock %}

templates/blog.html
{% extends 'base.html' %}
   {% load static %}
   {% block content %}
    <!-- ================================
    Start Content
    ================================= -->
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">My blog</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <section>

    <div class="lightBg">
        <div class="container">
          <div class="portfolioContentMain">
            <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
              {% for blog in blogs %}
              <div class="col-md-6 pColMain">
                <div class="pCol">

                      <a href="{% url 'blog:detail' blog.id %}">
                        <h2>{{ blog.title }}</h2>
                          </a>
                        <h6 >{{ blog.date|date:'M d Y'|upper }}</h6>
                      <h4>{{ blog.description|striptags|truncatechars:50 }}</h4>

                  <br>
                  <br>

                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>

    </section>
    <!-- ================================
    End Content
    ================================= -->
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
   {% load static %}
   {% block content %}
    <section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Send your message</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
        <form id="contactForm" method="POST" action="/contact/">
        {% csrf_token %}
            <label for="name">Name</label>
            {{form.name}}

            <label for="email">Email</label>
            {{form.email}}

            <label for="subject">Message</label>
            {{form.message}}

            <input class='btn btnPrimary' type="submit" value="Submit">
        </form>
    </div>
  </div>
</section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
   {% load static %}
   {% block content %}
    <!-- ================================
    End Navigation Bar
    ================================= -->

    <!-- ================================
    Start Content
    ================================= -->
    <section>
      <div class="bannerSection">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-auto order-md-last">
              <div class="bannerUserImg">
                <img src="{% static 'portfolio/images/myphoto.jpg' %}" alt="...">
              </div>
            </div>
            <div class="col-md">
              <div class="bannerContent">
                <h1 class="xlTitle pb-3">Hi, I’m Kubanychbek, <br> a Backend developer</h1>
                <p>I'm from Kyrgyzstan. I create websites with Python language and Django framework.</p>
                <div class="bannerBtnCol">
                  <div class="row">
                    <div class="col-auto">
                      <a download href="{% static 'portfolio/Talipov_Kubanychbek_cv.pdf' %}" class="btn btnPrimary">Download Resume</a>
                    </div>
                    <div class="col-auto">
                      <a href="{% url 'contact' %}" class="btn btnOutline">Contact</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="sectionSpace pt-0">
        <div class="container">
          <div class="row">
            <div class="col-md">
              <h4 class="smTitle pb-3">Skills</h4>
              <div class="progressCol">
                <div class="progressCard">
                  {% for s in skills %}
                  <div class="progressCol">
                    <span class="progressLbl">{{s.title}}</span>
                    <div class="row g-2 align-items-center">
                      <div class="col">
                        <div class="progress progressStyle">
                          <div class="progress-bar" role="progressbar" style="width: {{s.score}}%" aria-valuenow="{{s.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </div>
                      <div class="col-auto">
                        <span class="pLbl">{{s.score}}%</span>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="sectionSpaceSm lightBg">
        <div class="container">
          <div class="row pb-3">
            <div class="col">
              <h4 class="smText regular">Certificates</h4>
            </div>
            <div class="col-auto">
              <a href="javascript:void(0)" class="simpleLink">View all</a>
            </div>
          </div>

          <div class="sliderOuter">
            <div class="swiper certificatesSlider">
              <div class="swiper-wrapper">
                {% for c in certificates %}
                <div class="swiper-slide">
                  <div class="cardStyle1">
                    <h4 class="mdTitle cs1Title">
                      <a href="javascript:void(0)">{{c.title}}</a>
                    </h4>
                    <ul class="cardOptionCol">
                      <li>{{ c.date|date:'F jS Y'  }}</li>
                      <li>{{ c.name }}</li>
                    </ul>
                    <p>{{ c.description }}</p>
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>

            <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
            <div class="swiper-pagination swiperPaginationStyle posInitial"></div>

          </div>

        </div>
      </div>

    </section>


   {% endblock %}

templates/portfolio-detail.html
    <!-- ================================
    End Navigation Bar
    ================================= -->

    <!-- ================================
    Start Content
    ================================= -->
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">Portfolio title</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="sectionSpaceSm">
        <div class="container">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Aenean congue imperdiet lorem ut posuere. Maecenas nec accumsan 
          risus, quis luctus libero. Morbi a nulla ac felis scelerisque 
          feugiat quis vitae turpis. Vivamus nec augue vel enim scelerisque 
          cursus. Curabitur efficitur ipsum quis turpis bibendum egestas. 
          Nunc ac euismod dolor. Vestibulum nec ipsum fermentum, semper 
          quam eu, porttitor elit. Maecenas efficitur ex eget augue euismod 
          semper. Curabitur pharetra tortor vel orci volutpat semper. 
          Donec feugiat mauris ante. In hac habitasse platea dictumst.
          </p>
        </div>
      </div>
    </section>
    <!-- ================================
    End Content
    =================================

templates/portfolio.html
{% extends 'base.html' %}
   {% load static %}
   {% block content %}
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <div class="row g-4 g-md-3  align-items-center">
            <div class="col-md-6">
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3">Projects</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
        <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for i in projects %}
          <div class="portfolioCard">
          <div class="row g-4 align-items-center">
            <div class="col-md-auto">
              <div class="portfolioImgCol">
                  {% if i.url %}
                <a href="{{ i.url }}"><img src="{{ i.image.url }}" alt="..."></a>
                  {% else %}
                  <img src="{{ i.image.url }}" alt="...">
                  {% endif %}
              </div>
            </div>
            <div class="col-md">
              <div class="portfolioContentCol">
                <h4 class="lgTitle"><a href="{{ i.url }}">{{i.title}}</a></h4>
                <p>{{i.description}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        </div>
      </div>
    </div>
  </div>
  </section>
    <!-- ================================
    End Content
    ================================= -->

{% endblock %}